### ISSUE TITLE
Manage network errors

### ISSUE THREAD

**Issue by pimuzzo** [pimuzzo/git-siren#2]
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/xxxxxxx/issues?per_page=100&state=open&labels=bug (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x760f6870>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/home/pi/git_siren/github_adapter.py", line 37, in <module>
    for issue in issues:
  File "/usr/local/lib/python2.7/dist-packages/github3/structs.py", line 67, in __iter__                                                                                       
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request                                                                                     
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(110, 'ETIMEDOUT')",))                                                                                     
Traceback (most recent call last):
  File "/home/pi/git_siren/github_adapter.py", line 37, in <module>
    for issue in issues:
  File "/usr/local/lib/python2.7/dist-packages/github3/structs.py", line 67, in __iter__                                                                                       
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request                                                                                     
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))      
```

**Comment by pimuzzo** [comment]
```
Traceback (most recent call last):
  File "/home/pi/git_siren/github_adapter.py", line 37, in <module>
    for issue in issues:
  File "/usr/local/lib/python2.7/dist-packages/github3/structs.py", line 67, in __iter__                                                                                       
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request                                                                                     
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by pimuzzo** [comment]
```
Traceback (most recent call last):                                                                                                                                              
  File "/home/pi/git_siren/github_adapter.py", line 39, in <module>                                                                                                             
    for issue in issues:                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/github3/structs.py", line 67, in __iter__                                                                                        
    headers=headers)                                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/github3/models.py", line 185, in _get                                                                                            
    return self.session.get(url, **kwargs)                                                                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get                                                                                          
    return self.request('GET', url, **kwargs)                                                                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/github3/session.py", line 88, in request                                                                                         
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request                                                                                     
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cloudesire/frontend/issues?per_page=100&state=$pen&labels=bug (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x760f6870>: Failed to establish a new connection: [Errno -2] Name or servi$e not known',))
```
